# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: mySQL-database
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: example123
      MYSQL_USER: camilo
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: twitter-db
    volumes:
      - ./mysql:/var/lib/mysql